{% set name = "empack" %}
{% set version = "5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b4/07/d781d4084333b14311d35321a8706fa4a2b32f652b19f24d72676606342f/empack-{{ version }}.tar.gz
  sha256: 4766ca1811dee5c3b8def2a61ef906036bb1bf59868c1d00765647d8d8ce5628

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch
  run:
    - python >={{ python_min }}
    - typer
    - requests
    - platformdirs
    - pyyaml
    - networkx
    - click <8.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - empack
  commands:
    - empack --help

about:
  home: https://github.com/emscripten-forge/empack
  summary: CLI for packing a mamba environment with emsdk
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/emscripten-forge/empack

extra:
  recipe-maintainers:
    - JohanMabille
    - DerThorsten
    - wolfv
    - martinRenou
